### PR TITLE
ZCS-3100: Items of Certificate are shown in Theme tab on delegated admin

### PR DESCRIPTION
**Pull request by k-kato**

### CODE REVIEW

**Comment by k-kato** [comment]
Related to https://github.com/Zimbra/zm-admin-console/pull/35

**Review by silentsakky — APPROVED** [review]

**Comment by jiteshsojitra** [comment]
Looks good. Let's change review request summary like:
ZCS-3100: Items of Certificate are shown in Theme tab on delegated admin.

**Review by jiteshsojitra — APPROVED** [review]

**Comment by k-kato** [comment]
@jiteshsojitra - Is "review request summary" a title/subject of the PR? I changed the title.

**Comment by jiteshsojitra** [comment]
@k-kato - Looks good, yes generally high level summary of fix or if any bug/task associated.

**Review by kalpeshhpatel — APPROVED** [review]

**Pull request merged**
